### ISSUE TITLE
Installing python2 in the terminal of chcp 65001 will report an error

### ISSUE THREAD

**Issue by jan-bar** [version-fox/vfox-python#12]
![image](https://github.com/version-fox/vfox-python/assets/14202095/26cc4a07-91f0-41cd-ad8a-36bc5c01e670)

按下面方式可以成功，原因是我习惯在启动的终端执行`chcp 65001`，这样终端按照utf8字符显示，因此导致python执行命令报错。

```shell
chcp 936
vfox i python@2.7.18
```

网上都说`set PYTHONIOENCODING=UTF-8`可以解决，但实际我测试需要`chcp 936`才能解决。

**Comment by zhu0629** [comment]
安装pip的时候出错了, pip安装是官方提供的.
