### ISSUE TITLE
安装Python后，怎么修改pip install的C盘目录到其它盘呢

### ISSUE THREAD

**Issue by ljp190** [version-fox/vfox-python#16]
安装Python后，怎么修改pip install的C盘目录到其它盘呢

**Comment by zhu0629** [comment]
超出本项目讨论范围了, 

1. 建议参考pip官方文档, 设置安装目录
https://pip.pypa.io/en/stable/cli/pip_install/#cmdoption-t

2. 建议使用虚拟环境, 把pip安装的依赖安装到项目目录下.
https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/
