### ISSUE TITLE
安装python@3.12.3失败

### ISSUE THREAD

**Issue by LordHumphrey** [version-fox/vfox-python#2]
提示安装成功，但是目录是空的
![image](https://github.com/version-fox/vfox-python/assets/43847411/d70dea66-d0e1-487c-ad7c-013bb209e8b9)
![image](https://github.com/version-fox/vfox-python/assets/43847411/4683d0b4-20f6-42a8-82f0-2fcc8f012f07)

**Comment by LordHumphrey** [comment]
不如把exe安装方式完全改为使用压缩包安装？exe安装会有什么额外的好处呢？个人认为压缩包解压才是便携软件最合理的方案呢~

**Comment by aooohan** [comment]
> 不如把exe安装方式完全改为使用压缩包安装？exe安装会有什么额外的好处呢？个人认为压缩包解压才是便携软件最合理的方案呢~

当时是为了快速实现这个插件.  通过安装包可以减少pip的安装... 就不用手动处理了.

**Comment by LordHumphrey** [comment]
> > 不如把exe安装方式完全改为使用压缩包安装？exe安装会有什么额外的好处呢？个人认为压缩包解压才是便携软件最合理的方案呢~
> 
> 当时是为了快速实现这个插件. 通过安装包可以减少pip的安装... 就不用手动处理了.

pip这部分我觉得可以单独拆分为一个插件，有些人可能会使用[PDM](https://pdm-project.org/)，我对PDM不熟悉，但是从文档看，似乎不需要pip，所以将或许可以考虑将pip拆分为插件？

**Comment by aooohan** [comment]
可以来discord说, https://discord.com/invite/85c8ptYgb7

正好在讨论这个事情..

**Comment by LordHumphrey** [comment]
> 可以来discord说, https://discord.com/invite/85c8ptYgb7
> 
> 正好在讨论这个事情..

邀请无效？

**Comment by zhu0629** [comment]
#6
